[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "otimizador-formulacoes"
version = "1.0.0"
description = "Otimizador de formulações de custo mínimo usando Streamlit e PuLP."
authors = [
    {name = "Levi", email = "seu.email@exemplo.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.8"
keywords = ["otimizacao", "streamlit", "pulP", "r&d", "formulacao"]

# Adicione esta linha para resolver o erro 'Multiple top-level modules discovered'
py-modules = ["app_streamlit", "otimizacao_motor"] 
# -------------------------------------------------------------------------

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License", # Vamos deixar a recomendação do SPDX para depois
    "Operating System :: OS Independent",
]

dependencies = [
    "streamlit",
    "pandas",
    "openpyxl",
    "pulp",
    "plotly", 
]

[tool.uv]