[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "otimizador-formulacoes"
version = "1.0.0"
description = "Otimizador de formulações de custo mínimo usando Streamlit e PuLP."
authors = [
    {name = "Levi", email = "seu.email@exemplo.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.8"
keywords = ["otimizacao", "streamlit", "pulP", "r&d", "formulacao"]
# py-modules FOI REMOVIDO DAQUI
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "streamlit",
    "pandas",
    "openpyxl",
    "pulp",
    "plotly",
]

# NOVO: Seção para setuptools para listar os módulos
[tool.setuptools]
py-modules = ["app_streamlit", "otimizacao_motor"] 
# ---------------------------------------------------

[tool.uv]